/**
 * GENERATED BY `pnpm stats` - do not edit by hand.
 *
 * The numbers on the home page must come from the real suite, not from someone's
 * memory. `pnpm stats --check` fails in CI if the file has fallen behind.
 */
export const TEST_COUNT = 875;
export const PACKAGE_COUNT = 6;
export const CATALOG_COUNT = 211;
export const RUNTIME_DEPENDENCIES = 0;
