/**
 * Packaging output for native targets.
 *
 * RaptorForge does not build installers - it writes down, once and verifiably,
 * what has to be built. The package plan comes from the adapter, and the CI
 * workflow is generated from that same plan, so the two can never drift: adding
 * a platform to the adapter changes the workflow on the next generation instead
 * of leaving a stale matrix behind.
 */
import { planDesktopPackages } from "@raptor/host/desktop";
import type { HostManifest, PackagePlan } from "@raptor/host";
import { planMobilePackages } from "@raptor/host/mobile";

export function planFor(manifest: HostManifest): PackagePlan {
  return manifest.target === "desktop" ? planDesktopPackages(manifest) : planMobilePackages(manifest);
}

/** The descriptor written to `hosts/<target>/packaging.json`. */
export function renderPackaging(plan: PackagePlan): string {
  return (
    JSON.stringify(
      {
        target: plan.target,
        bundleId: plan.bundleId,
        version: plan.version,
        runners: plan.runners,
        mustSign: plan.mustSign,
        artifacts: plan.artifacts,
      },
      null,
      2,
    ) + "\n"
  );
}

/**
 * A GitHub Actions workflow built from the plan.
 *
 * Two things are deliberate. Signing secrets are referenced but never defaulted:
 * a workflow that silently produces unsigned artifacts is worse than one that
 * fails. And every job ends with a smoke step, because roadmap section 7 asks CI
 * to prove the installer works, not merely that it was produced.
 */
export function renderWorkflow(plan: PackagePlan, appName: string): string {
  const byRunner = new Map<string, typeof plan.artifacts>();
  for (const artifact of plan.artifacts) {
    const existing = byRunner.get(artifact.runner);
    if (existing) byRunner.set(artifact.runner, [...existing, artifact]);
    else byRunner.set(artifact.runner, [artifact]);
  }

  const jobs = [...byRunner.entries()].map(([runner, artifacts]) => {
    const platform = artifacts[0]!.platform;
    const needsSigning = artifacts.some((artifact) => artifact.signing !== "optional");
    return [
      `  ${platform}:`,
      `    runs-on: ${runner}`,
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - uses: actions/setup-node@v4",
      "        with:",
      "          node-version: 24",
      "      - name: Install dependencies",
      "        run: npm ci",
      "      - name: Build application bundle",
      "        run: npm run build",
      `      - name: Package ${platform} artifacts`,
      `        run: raptor-package ${platform} --plan hosts/${plan.target}/packaging.json`,
      ...(needsSigning
        ? [
            "        env:",
            "          RAPTOR_SIGNING_IDENTITY: ${{ secrets.RAPTOR_SIGNING_IDENTITY }}",
            "          RAPTOR_SIGNING_KEY: ${{ secrets.RAPTOR_SIGNING_KEY }}",
          ]
        : []),
      "      - name: Smoke test the packaged application",
      `        run: raptor-package smoke ${platform} --plan hosts/${plan.target}/packaging.json`,
      "      - uses: actions/upload-artifact@v4",
      "        with:",
      `          name: ${platform}`,
      "          path: |",
      ...artifacts.map((artifact) => `            dist/${plan.target}/${artifact.filename}`),
    ].join("\n");
  });

  return [
    `name: ${appName} installers`,
    "",
    "# Generated by RaptorForge from hosts/" + plan.target + "/packaging.json.",
    "# Regenerate instead of editing by hand: the plan is the source of truth.",
    "#",
    "# `raptor-package` ships with the native host adapter. Until that binary is",
    "# installed on the runners, these jobs fail loudly at the packaging step -",
    "# which is the honest outcome, rather than uploading nothing and passing.",
    "",
    "on:",
    "  push:",
    "    tags:",
    '      - "v*"',
    "  workflow_dispatch:",
    "",
    "jobs:",
    ...jobs,
    "",
  ].join("\n");
}
