/**
 * Multi-target code generation (RaptorEngine whitepaper section 9, 15).
 *
 * A key goal: browser, server and wire are generated from the SAME semantic
 * graph, reducing the drift between client, server and protocol. The three
 * emitters live here; they all consume the same optimized IR.
 */
import {
  exprToJs,
  type IRModule,
  type IRComponent,
  type IRElement,
  type IRChild,
  type Expr,
} from "@raptor/engine/compiler";

// --- Common helpers --------------------------------------------------------

function reactiveNames(comp: IRComponent): Set<string> {
  const set = new Set<string>();
  for (const s of comp.signals) set.add(s.name);
  for (const d of comp.deriveds) set.add(d.name);
  for (const ss of comp.serverSignals) set.add(ss.name);
  return set;
}

/** Translates a signal mutation (`count++`, `count += 1`, `x = v`) into runtime code. */
function writeToJs(handler: Expr, reactive: Set<string>): string {
  if (handler.kind === "Update" && handler.arg.kind === "Ident" && reactive.has(handler.arg.name)) {
    const name = handler.arg.name;
    const op = handler.op === "++" ? "+" : "-";
    return `${name}.set(${name}() ${op} 1)`;
  }
  if (handler.kind === "Assign" && handler.target.kind === "Ident" && reactive.has(handler.target.name)) {
    const name = handler.target.name;
    const valueJs = exprToJs(handler.value, reactive);
    if (handler.op === "=") return `${name}.set(${valueJs})`;
    const binop = handler.op[0]!; // += -= *= /= %=
    return `${name}.set((${name}() ${binop} ${valueJs}))`;
  }
  return exprToJs(handler, reactive);
}

// --- Browser codegen -------------------------------------------------------

class BrowserEmitter {
  private readonly reactive: Set<string>;
  private readonly lines: string[];
  private counter: number;
  constructor(reactive: Set<string>) {
    this.reactive = reactive;
    this.lines = [];
    this.counter = 0;
  }

  emitElement(el: IRElement): string {
    const varName = `_e${this.counter++}`;
    this.lines.push(`  const ${varName} = createElement(${JSON.stringify(el.tag)});`);

    const props: string[] = [];
    for (const a of el.attrs) {
      if (a.expr) props.push(`${JSON.stringify(a.name)}: () => ${exprToJs(a.expr, this.reactive)}`);
      else props.push(`${JSON.stringify(a.name)}: ${JSON.stringify(a.value ?? "")}`);
    }
    for (const ev of el.events) {
      props.push(`${JSON.stringify("on:" + ev.event)}: () => ${writeToJs(ev.handler, this.reactive)}`);
    }
    if (props.length > 0) {
      this.lines.push(`  applyProps(${varName}, { ${props.join(", ")} });`);
    }

    for (const child of el.children as IRChild[]) {
      if (child.kind === "Element") {
        const childVar = this.emitElement(child);
        this.lines.push(`  mountChild(${varName}, ${childVar}, null);`);
      } else if (child.expr) {
        this.lines.push(`  mountChild(${varName}, () => ${exprToJs(child.expr, this.reactive)}, null);`);
      } else {
        this.lines.push(`  mountChild(${varName}, ${JSON.stringify(child.text ?? "")}, null);`);
      }
    }
    return varName;
  }

  build(comp: IRComponent): string {
    const decls: string[] = [];
    for (const s of comp.signals) {
      decls.push(`  const ${s.name} = state(${exprToJs(s.init, new Set())});`);
    }
    for (const ss of comp.serverSignals) {
      decls.push(
        `  const ${ss.name} = state(0); // <- RAS ${JSON.stringify(ss.address)} schema ${ss.schema ?? "any"}`,
      );
    }
    for (const d of comp.deriveds) {
      decls.push(`  const ${d.name} = derived(() => ${exprToJs(d.expr, this.reactive)});`);
    }
    for (const ef of comp.effects) {
      decls.push(`  effect(() => ${exprToJs(ef.expr, this.reactive)});`);
    }
    const rootVar = this.emitElement(comp.root);
    return [
      `export function ${comp.name}() {`,
      ...decls,
      ...this.lines,
      `  return ${rootVar};`,
      `}`,
    ].join("\n");
  }
}

/** Emits the browser module: component functions that build fine-grained DOM. */
export function emitBrowser(module: IRModule): string {
  const header =
    `// generated by @raptor/engine (browser target)\n` +
    `import { state, derived, effect } from "raptorjs";\n` +
    `import { createElement, applyProps, mountChild } from "raptorjs/dom";\n`;
  const bodies = module.components.map((c) => new BrowserEmitter(reactiveNames(c)).build(c));
  return header + "\n" + bodies.join("\n\n") + "\n";
}

// --- Server codegen --------------------------------------------------------

export interface ServerProducer {
  address: string;
  schema: string | null;
}

export interface ServerOutput {
  code: string;
  producers: ServerProducer[];
}

/** Emits the registration of server-side producers (server signals). */
export function emitServer(module: IRModule): ServerOutput {
  const producers: ServerProducer[] = [];
  for (const c of module.components) {
    for (const ss of c.serverSignals) producers.push({ address: ss.address, schema: ss.schema });
  }
  const regs = producers
    .map((p) => `  rt.producer(${JSON.stringify(p.address)}, { schema: ${JSON.stringify(p.schema)} });`)
    .join("\n");
  const code =
    `// generated by @raptor/engine (server target)\n` +
    `export function registerServer(rt) {\n${regs}\n}\n`;
  return { code, producers };
}

// --- Wire codegen ----------------------------------------------------------

export interface WireAddress {
  logical: string;
  ras: string;
  decoderSlot: number;
  schema: string | null;
}

export interface WireManifest {
  schemas: string[];
  addresses: WireAddress[];
}

/**
 * Emits the wire manifest: schema IDs, RAS addresses (Reactive Address Space)
 * and precompiled decoder slots (15: compiled network bindings). Addresses
 * start at 0x18A1 (the example from the whitepaper) and grow deterministically.
 */
export function emitWireManifest(module: IRModule): WireManifest {
  const schemas = new Set<string>();
  const addresses: WireAddress[] = [];
  let ras = 0x18a1;
  let slot = 0;
  for (const c of module.components) {
    for (const ss of c.serverSignals) {
      if (ss.schema) schemas.add(ss.schema);
      addresses.push({
        logical: ss.address,
        ras: "0x" + ras.toString(16).toUpperCase(),
        decoderSlot: slot,
        schema: ss.schema,
      });
      ras++;
      slot++;
    }
  }
  return { schemas: [...schemas], addresses };
}
